project:
  type: website

website:
  title: "Ahana Samat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: Sub1.qmd
        text: my homework 1
      - href: sub2.qmd
        text: my homework 2
      - href: Assignment1.qmd
        text: Assignment 1
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

